services:
  wimalina-web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "${PORT:-8080}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
